import '@/styles/app.scss';

import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';

import { poppins, rubik } from '@/constant/font';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {
  let messages;

  try {
    // messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    // notFound();
  }
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <NextIntlClientProvider locale={locale}>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
