import Layout from "@/layout/Layout";
import "@/styles/index.scss";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Poppins } from "next/font/google";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function LocaleLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: any;
}) {
	let messages;

	try {
		// messages = (await import(`../../../messages/${locale}.json`)).default;
	} catch (error) {
		// notFound();
	}
	return (
		<html lang='en'>
			<body className={`${poppins.className} bg-be`}>
				<NextIntlClientProvider locale={locale}>
					<Layout>{children}</Layout>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
